In [31]:
import pandas as pd
import matplotlib.pyplot as plt

In [21]:
# Replace 'file_path.csv' with the actual file path
file_path = r"C:\Users\Ahmed laptop\Desktop\USPN\machine leanring\oecd_bli_2015.csv"

# Read the CSV file into a DataFrame
df_oecd = pd.read_csv(file_path)

# Display the first few rows
print(df_oecd.head())

  LOCATION         Country INDICATOR                           Indicator  \
0      AUS       Australia   HO_BASE  Dwellings without basic facilities
1      AUT         Austria   HO_BASE  Dwellings without basic facilities
2      BEL         Belgium   HO_BASE  Dwellings without basic facilities
3      CAN          Canada   HO_BASE  Dwellings without basic facilities
4      CZE  Czech Republic   HO_BASE  Dwellings without basic facilities

  MEASURE Measure INEQUALITY Inequality Unit Code        Unit  PowerCode Code  \
0       L   Value        TOT      Total        PC  Percentage               0
1       L   Value        TOT      Total        PC  Percentage               0
2       L   Value        TOT      Total        PC  Percentage               0
3       L   Value        TOT      Total        PC  Percentage               0
4       L   Value        TOT      Total        PC  Percentage               0

  PowerCode  Reference Period Code  Reference Period  Value Flag Codes  \
0     units                    NaN               NaN    1.1          E
1     units                    NaN               NaN    1.0        NaN
2     units                    NaN               NaN    2.0        NaN
3     units                    NaN               NaN    0.2        NaN
4     units                    NaN               NaN    0.9        NaN

             Flags
0  Estimated value
1              NaN
2              NaN
3              NaN
4              NaN

In [22]:
df_oecd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3292 entries, 0 to 3291
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   LOCATION               3292 non-null   object
 1   Country                3292 non-null   object
 2   INDICATOR              3292 non-null   object
 3   Indicator              3292 non-null   object
 4   MEASURE                3292 non-null   object
 5   Measure                3292 non-null   object
 6   INEQUALITY             3292 non-null   object
 7   Inequality             3292 non-null   object
 8   Unit Code              3292 non-null   object
 9   Unit                   3292 non-null   object
 10  PowerCode Code         3292 non-null   int64
 11  PowerCode              3292 non-null   object
 12  Reference Period Code  0 non-null      float64
 13  Reference Period       0 non-null      float64
 14  Value                  3292 non-null   float64
 15  Flag Codes             1120 non-null   object
 16  Flags                  1120 non-null   object
dtypes: float64(3), int64(1), object(13)
memory usage: 437.3+ KB

In [23]:
# File path
file = r"C:\Users\Ahmed laptop\Desktop\USPN\machine leanring\gdp_per_capita.csv"

# Read the CSV file with a specified encoding
df_gdp = pd.read_csv(file, sep='\t', encoding='ISO-8859-1', na_values="n/a")

# Display the first few rows
print(df_gdp.head())

               Country                                 Subject Descriptor  \
0          Afghanistan  Gross domestic product per capita, current prices
1              Albania  Gross domestic product per capita, current prices
2              Algeria  Gross domestic product per capita, current prices
3               Angola  Gross domestic product per capita, current prices
4  Antigua and Barbuda  Gross domestic product per capita, current prices

          Units  Scale                      Country/Series-specific Notes  \
0  U.S. dollars  Units  See notes for:  Gross domestic product, curren...
1  U.S. dollars  Units  See notes for:  Gross domestic product, curren...
2  U.S. dollars  Units  See notes for:  Gross domestic product, curren...
3  U.S. dollars  Units  See notes for:  Gross domestic product, curren...
4  U.S. dollars  Units  See notes for:  Gross domestic product, curren...

         2015  Estimates Start After
0     599.994                 2013.0
1   3,995.383                 2010.0
2   4,318.135                 2014.0
3   4,100.315                 2014.0
4  14,414.302                 2011.0

In [ ]:
def prepare_country_stats(oecd_bli, gdp_per_capita):

    oecd_bli = oecd_bli[oecd_bli["INEQUALITY"]=="TOT"]

    oecd_bli = oecd_bli.pivot(index="Country", columns="Indicator", values="Value")

    gdp_per_capita.rename(columns={"2015": "GDP per capita"}, inplace=True)

    gdp_per_capita.set_index("Country", inplace=True)

    full_country_stats = pd.merge(left=oecd_bli, right=gdp_per_capita,

                                  left_index=True, right_index=True)

    full_country_stats.sort_values(by="GDP per capita", inplace=True)

    remove_indices = [0, 1, 6, 8, 33, 34, 35]

    keep_indices = list(set(range(36)) - set(remove_indices))

    return full_country_stats[["GDP per capita", 'Life satisfaction']].iloc[keep_indices]

In [25]:
country_df= prepare_country_stats(df_oecd, df_gdp)

In [26]:
country_df

                GDP per capita  Life satisfaction
Country
Poland              12,495.334                5.8
Chile               13,340.905                6.7
Slovak Republic     15,991.736                6.1
Czech Republic      17,256.918                6.5
Greece              18,064.288                4.8
Slovenia            20,732.482                5.7
Spain               25,864.721                6.5
Korea               27,195.197                5.8
Italy               29,866.581                6.0
Japan               32,485.545                5.9
Israel              35,343.336                7.4
New Zealand         37,044.891                7.3
France              37,675.006                6.5
Belgium             40,106.632                6.9
Germany             40,996.511                7.0
Finland             41,973.988                7.4
Canada              43,331.961                7.3
Netherlands         43,603.115                7.3
Austria             43,724.031                6.9
United Kingdom      43,770.688                6.8
Sweden              49,866.266                7.2
Iceland             50,854.583                7.5
Australia           50,961.865                7.3
Ireland             51,350.744                7.0
Denmark             52,114.165                7.5
United States       55,805.204                7.2
Norway              74,822.106                7.4
Brazil               8,669.998                7.0
Switzerland         80,675.308                7.5

In [27]:
import numpy as np

In [28]:
Y=np.c_[country_df["GDP per capita"]]

In [ ]:
X=np.c